### ISSUE TITLE
Proper Push Notifications

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#12]
We need to be able to send local push notifications after any of the following events occur:
- Badge Captured/Read
- Boscloner connection lost
- Boscloner connection restored
(All of these are implemented in the iOS code)

Notifications do not need to appear to the user while they are actively using the Boscloner app in the foreground. However, when the app is in the background, or the user has their screen off, or they are at the lock screen, this is when the push notifications need to be visible to the user, followed by the default notification sound set by their mobile device.

**Comment by Boscloner** [comment]
On my device, I am not alerted via push/local notifications when the connection is lost or the connection restored.

I do receive notifications when a badge is captured though. That particular notification seems to be functioning as intended.

**Comment by aleksamarkoni** [comment]
This should be fixed now.
