### ISSUE TITLE
Set Variable to "0000000000" After a Write from History or Custom Write is performed

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#16]
If you were to type into Custom Write:
0102030405

That string would appropriately be sent to the Boscloner.

If you were to then open Custom Write, but submit it while blank/empty, it would send the previous string to the board, but would say, "Custom ID Written:   " in the Home Screen / Terminal view.

If we set this string to 10 zeros, "0000000000" after the data is successfully sent to the board, this issue would resolve itself, while allowing the "Custom ID Written:   " text to display all zeros in the home screen / terminal view.

**Comment by aleksamarkoni** [comment]
Hi @philimanjaro, I am sorry I forgot what we discussed here. I will check to see why we send empty data, and prevent sending of data which length is zero.

**Comment by Boscloner** [comment]
Thanks @aleksamarkoni 

Essentially, we need to make sure that we are sending 10 badge characters no matter what, from both the history page and the Custom Write box.

Scenario 1:
A user selects the Custom Write Box and enters in: "123456"

We need to, in the app, pad the rest of the string with zeros. So, again, if the user enters in "123456" in the app, the actual data that is sent to the board should be "1234560000".

Likewise, if the user enters "A1BC2" to the board (5 characters), the app needs to ensure that the data sent to the board is padded with zeros: "A1BC200000".


As a side note, it isn't quite as simple as reading the string and determining how many characters are in it...because users occasionally enter in colons ":" ... which are stripped out and ignored when it reaches the board. So we need to make sure that colons don't count as a character when counting the amount of characters a user enters.

**Comment by aleksamarkoni** [comment]
Well I could also strip the ":" on my end, and then append zeros. That will be really easy to implement.

**Comment by aleksamarkoni** [comment]
I have striped the ":" from every command that we send, and then if what's left is longer than 10 characters I append the appropriate amount of zeros. Can you please recheck how this looks like on your end.

**Comment by Boscloner** [comment]
This appears to be working as expected in my test cases, thank you!
