### ISSUE TITLE
Automatically re-establish BT connection in the background

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#17]
While the app has the ability to re-establish the Bluetooth connection (after it has been lost) while sitting at the home screen, it doesn't appear to have this ability while the user is at the History screen.

We need to make sure that the connectivity state, and automatic restoration of the the connectivity state is handled in the background at all times...regardless of the screen/page the user is on, and regardless of if the app is open, background, the phone's screen is turned off, or the user is at the lock screen. The Bluetooth state should always be managed, and appropriately logged via push/local notifications.

**Comment by aleksamarkoni** [comment]
This might happen for so many reasons. Every time when there is some error, wrong condition or false scan we should retry the scan and start again. Error checks are much better now. We will need to test this more using real hardware but I would say it will work now.

**Comment by Boscloner** [comment]
I've tested this on the various pages within the app, the Android device home screen, and with the screen off and on the lock screen. It seems to reconnect very well. We need to work on notifying the user when a connection is lost and when it is restored, but that will be handled in a different issue ticket. Thanks!
