### ISSUE TITLE
History View Table, switch direction and order

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#18]
For the history view:

The newest/most recent captured badge should always appear at the top of the screen. 

If the History page looked like this:

Badge1 _(Most Recent Capture)_
Badge2 _(Captured 2 minutes ago)_
Badge3 _(Captured 3 minutes ago)_
Badge4 _(Captured 4 minutes ago)_

Then, the User captured another badge...the history page would then look like this:

Badge0 _(Most Recent Capture)_
Badge1 _(Captured 1 minutes ago)_
Badge2 _(Captured 2 minutes ago)_
Badge3 _(Captured 3 minutes ago)_
Badge4 _(Captured 4 minutes ago)_

**Comment by aleksamarkoni** [comment]
We just need to remove the line linearLayoutManager.setStackFromEnd(true); from the history fragment.

**Comment by aleksamarkoni** [comment]
Done

**Comment by Boscloner** [comment]
This doesn't appear to be fixed. When I scan a new badge, it shows up at the bottom of the history view. I'd like the most recent badge to be added to the top of the stack, as if each newly captured badge was a pancake being tossed on a stack of other pancakes. :)

**Comment by aleksamarkoni** [comment]
Done
