### ISSUE TITLE
COSMETIC - Date Format in "History"

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#2]
The date format in history view should be truncated so that it does not take up multiple lines.

The time and date should be formatted as such:
YYYY-MM-DD   HH:MM:SS

Y = Year
M = Month
D = Day
H = Hour
M = Minute
S = Second

So, a proper timestamp would look something like:
2018-06-06   15:45:12

**Comment by aleksamarkoni** [comment]
Done

**Comment by Boscloner** [comment]
Thanks for taking care of this, it's almost right, but not quite.

Currently, the date is showing up just like this:
2018-07-01T09:29:00.912

Due to the amount of characters, it is wrapping the text to a second line. There are also characters in there that are not part of the requested format. As in, the "T" shouldn't be in there, and the ".912" (in the example I provided above)

We have two options here, feel free to select the one that you think would look better across more devices.

**Option 1:**
Remove the unnecessary characters...namely the "T" and the '.XXX' that appears at the end of the timestamp. This should provide enough space so that the text does not wrap to a second line.


**Option 2:**
Use two lines. The top line will contain HH:MM:SS. While the bottom line will contain YYYY-MM-DD.
