### ISSUE TITLE
Write From History Confirmation Box - Cancel Button

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#20]
When in the history screen and you select an entry to write from, a dialog box pops up. 

This dialog box has an "OK" option, but should also have a "Cancel" option. I know tapping outside of the popup box accomplishes this, but it isn't very clear. 

Please add a cancel button to the popup box.

Also, when selecting a badge from history, the keyboard automatically pops up. Can we stop the keyboard from automatically popping up?  Unless the user taps in the box to 'edit' the badge, the keyboard does not need to appear.

**Comment by aleksamarkoni** [comment]
I am sorry, but I can't remove that keyboard. I know it sounds strange, but we are using library for those dialogs since android default ones sucks. And as you can see that library does not have an option to dismiss keyboards https://github.com/afollestad/material-dialogs/issues/1211.
