### ISSUE TITLE
Custom Write Dialog Box - Text Changes

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#21]
Please modify the text of the Custom Write Dialog box to mirror how the iOS version appears (as far as text content is concerned)

Also, please add a 'Cancel' button to this prompt.

See attached image for reference.
![img_2227](https://user-images.githubusercontent.com/37783993/42136475-bd842542-7d21-11e8-8491-d9b15401950f.PNG)

**Comment by Boscloner** [comment]
Thanks. 

Just one thing to fix before this can be marked as resolved:

There is a typo. The app currently shows: "Enter Custom Budge ID", instead of "Enter Custom Badge ID"

**Comment by aleksamarkoni** [comment]
Fixed typo :)
