### ISSUE TITLE
Colors of Text and Icons - From Purple/blue to Black

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#22]
To add uniformity across the iOS and Android versions, please replace all instances of that purple/blue color with Black.

For example, when inside the Boscloner Android app, the following elements are purple/blue that need to be changed to black:

- The top status bar

- The "Custom Write" label text on the home screen

- The "AutoClone" label text on the home screen

- The "Tab Bar"  on the bottom of the screen that has "Home, History, and Settings". The selected item is always purple, please change to black.

- The "Share" and "Delete" label text on the "History" page need to be removed altogether and only the icons should remain. (After deleting the text labels there, please slightly increase the size of the icons to make them easier to tap)

**Comment by aleksamarkoni** [comment]
Done

**Comment by Boscloner** [comment]
Thanks for updating this. A few minor adjustments are still necessary...

On the history screen, the Share and Delete icons need to be smaller, similar in size to the iOS version and the bar that they sit in needs to be just a little smaller. It could be similar in size to the tab navigation bar below it.

Also, the "Custom Write" and "AutoClone" text on the home screen needs to be a little bit smaller.  A little bit smaller than the "Boscloner" title text on top of the screen.

**Comment by aleksamarkoni** [comment]
I changed the size of share and delete icons in history fragment from 48 x 48 to 30 x 35. It's dimensions are now similar to icons in the tab navigation below.
Also, "Custom Write" and "AutoClone" text is now smaller (from 24sp to 20sp). If we need to change dimensions again, let me now and I'll fix it.

**Comment by Boscloner** [comment]
I love the size of the icons. It looks great! Thank you.

One last request in regards to the "Delete History" dialog box.

It currently shows up like this:
Delete history
Are you sure you want to delete history


I'd like it to show up like this (notice the addition of the Question Mark, added text, and capitalization...changes in bold):
Delete **H**istory
Are you sure you want to delete **all entries from the** history **file?**

After that, we can resolve/close this ticket. Thank you.

**Comment by aleksamarkoni** [comment]
I am closing this one, it will be included with the next version.
