### ISSUE TITLE
When switching from the History page to the Home page, an alert is given...

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#25]
This one is a bit odd.

If connected to the Boscloner and the user goes into the History screen, then switches back over to the Home screen...once the user switches back to the home screen, an alert sound is heard. 

It doesnt appear that anything is being sent to the board during this...so I have no idea why it makes an alert sound.  I can switch back and forth between History and Home as many times as I'd like, and the same alert is given indefinitely.

Something about switching between those screens seems to trigger some kind of alert, but i don't know what it is exactly. Nothing shows up on the app, but my phone vibrates and makes an alert sound.

**Comment by aleksamarkoni** [comment]
I guess that's some kind of notification that I send every time when we open home page. I will try to see what this is, but I think I know what is the problem.

**Comment by aleksamarkoni** [comment]
This should be fixed now, I was updating the notification with the current state, everytime you open the home fragment.

**Comment by Boscloner** [comment]
Excellent! The issue has vanished. Thanks for squashing that one.
