### ISSUE TITLE
Check Connection Status to Bluetooth Prior to Performing Write Operations

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#8]
Let's add a check to ensure that the bluetooth connection is established prior to allowing the user to send write commands.

In the the iOS app, this is achieved by checking the connected state when a user taps on things like writing from history, autoclone toggle, or custom write:

    @IBAction func customWriteIcon(_ sender: UIButton) {
        if connectedPeripheral?.state != CBPeripheralState.connected {
        notConnectedWarning()
        } else {
            showInputDialog()
        }
    }

Essentially, if the device is connected, the operation continues. If it is not connected, a popup dialog box appears to the user and states that the Boscloner is not connected. Please view the iOS Swift code below on the box that pops up when the user tries to perform an action while in a disconnected state:

 // BLE Device Not Connected Dialog Alert Pop-up
    func notConnectedWarning() {
        let alertController = UIAlertController(title: "Boscloner Unavailable (BLE)", message: "Ensure the Boscloner boards are powered on and within range.", preferredStyle: .alert)
        
        //the cancel action doing nothing
        let cancelAction = UIAlertAction(title: "OK", style: .cancel) { (_) in }
        
        //adding the action to dialogbox
        alertController.addAction(cancelAction)
        
        //finally presenting the dialog box
        self.present(alertController, animated: true, completion: nil)
    }

**Comment by Boscloner** [comment]
I do not receive this popup when in the history screen and when tapping a badge entry when in a disconnected state.

**Comment by aleksamarkoni** [comment]
Ok I see, I did not implement it like this. I was just disregarding the action is the boslconer is not connected, but you could still initiate it. I will change a logic a bit to support this.

**Comment by aleksamarkoni** [comment]
Ok this is now done, if you try to write from history, there is a dialog that will pop up if the device is disconnected. And you can't see the autoclone and custom write buttons until you are not connected with the device.

**Comment by Boscloner** [comment]
Works great now. Thank you.
